version: "3.9"

networks:
    api-base-network:
        driver: bridge

x-logging: &default-logging
    options:
        max-size: "12m"
        max-file: "5"
    driver: json-file

services:
    ### redis ###########################################
    redis:
        image: "redis:6"
        logging: *default-logging
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - ${DATA_PATH_HOST}/redis:/data
        restart: ${RESTART_CONTAINERS}
        networks:
            - api-base-network

    ### MariaDB ##############################################
    mariadb:
        build:
            context: ./mariadb
            args:
                - MARIADB_VERSION=${MARIADB_VERSION}
        logging: *default-logging
        volumes:
            - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
            - ${MARIADB_LOGS_PATH}:/var/log/mariadb${CONTAINER_PATH_FLAG}
        environment:
            - MYSQL_USER=${MARIADB_USER}
            - MYSQL_PASSWORD=${MARIADB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        tty: true
        restart: ${RESTART_CONTAINERS}
        ports:
            - "${MARIADB_PORT}:3306"
        networks:
            - api-base-network

    ### phpMyAdmin ###########################################
    phpmyadmin:
        logging: *default-logging
        build: ./phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}
        volumes:
            - ${DATA_PATH_HOST}/phpmyadmin/sessions:/sessions
        expose:
            - "80"
        depends_on:
            - mariadb
        restart: ${RESTART_CONTAINERS}
        networks:
            - api-base-network

    ### NGINX Server #########################################
    nginx:
        logging: *default-logging
        build:
            context: ./nginx
            args:
                - PUID=${USER_PUID}
                - PGID=${USER_PGID}
        volumes:
            - ${APPS_PATH_HOST}/${API_SUBPATH_HOST}:${CODE_PATH_CONTAINER}/${API_SUBPATH_HOST}${CONTAINER_PATH_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx${CONTAINER_PATH_FLAG}
            - ${NGINX_CONF_PATH}/nginx.conf:/etc/nginx/nginx.conf${CONTAINER_PATH_FLAG}
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available${CONTAINER_PATH_FLAG}
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl${CONTAINER_PATH_FLAG}
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
            - php-fpm
        links:
            - phpmyadmin
        tty: true
        restart: ${RESTART_CONTAINERS}
        networks:
            - api-base-network

    ### PHP-FPM  ##############################################
    php-fpm:
        logging: *default-logging
        expose:
            - "9000"
        tty: true
        restart: ${RESTART_CONTAINERS}
        environment:
            - PHP_INI_DIR=/usr/local/etc/php
        networks:
            - api-base-network
        build:
            context: ./php-fpm
            dockerfile: ./Dockerfile
            args:
                - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
                - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE}
                - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
                - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
                - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
                - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
                - INSTALL_IMAGE_OPTIMIZERS=${PHP_FPM_INSTALL_IMAGE_OPTIMIZERS}
                - INSTALL_IMAGEMAGICK=${PHP_FPM_INSTALL_IMAGEMAGICK}
                - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
                - PUID=${USER_PUID}
                - PGID=${USER_PGID}
        volumes:
            - ${APPS_PATH_HOST}/${API_SUBPATH_HOST}:${CODE_PATH_CONTAINER}/${API_SUBPATH_HOST}${CONTAINER_PATH_FLAG}
            - ${PHP_FPM_LOGS_PATH}:/var/log/php-fpm${CONTAINER_PATH_FLAG}

    ### Workspace Utilities ##################################
    workspace:
        logging: *default-logging
        volumes:
            - ${APPS_PATH_HOST}/${API_SUBPATH_HOST}:${CODE_PATH_CONTAINER}/${API_SUBPATH_HOST}${CONTAINER_PATH_FLAG}
        tty: true
        restart: ${RESTART_CONTAINERS}
        networks:
            - api-base-network
        build:
            context: ./workspace
            dockerfile: ./Dockerfile
            args:
                - INSTALL_XDEBUG=${WORKSPACE_INSTALL_XDEBUG}
                - INSTALL_PHPREDIS=${WORKSPACE_INSTALL_PHPREDIS}
                - INSTALL_IMAGE_OPTIMIZERS=${WORKSPACE_INSTALL_IMAGE_OPTIMIZERS}
                - INSTALL_IMAGEMAGICK=${WORKSPACE_INSTALL_IMAGEMAGICK}
                - INSTALL_EXIF=${WORKSPACE_INSTALL_EXIF}
                - INSTALL_LIBPNG=${WORKSPACE_INSTALL_LIBPNG}
                - PUID=${USER_PUID}
                - PGID=${USER_PGID}
        environment:
            - PHP_INI_DIR=/etc/php/8.1

    ### PHP Worker ############################################
    php-worker:
        logging: *default-logging
        environment:
            - PHP_INI_DIR=/usr/local/etc/php
        depends_on:
            - php-fpm
        tty: true
        restart: ${RESTART_CONTAINERS}
        networks:
            - api-base-network
        build:
            context: ./php-worker
            dockerfile: ./Dockerfile
            args:
                - INSTALL_PHPREDIS=${PHP_WORKER_INSTALL_PHPREDIS}
                - INSTALL_OPCACHE=${PHP_WORKER_INSTALL_OPCACHE}
                - INSTALL_IMAGE_OPTIMIZERS=${PHP_WORKER_INSTALL_IMAGE_OPTIMIZERS}
                - INSTALL_BCMATH=${PHP_WORKER_INSTALL_BCMATH}
                - INSTALL_IMAGEMAGICK=${PHP_WORKER_INSTALL_IMAGEMAGICK}
                - INSTALL_EXIF=${PHP_WORKER_INSTALL_EXIF}
                - INSTALL_ZIP_ARCHIVE=${PHP_WORKER_INSTALL_ZIP_ARCHIVE}
                - INSTALL_INTL=${PHP_WORKER_INSTALL_INTL}
                - PUID=${USER_PUID}
                - PGID=${USER_PGID}
        expose:
            - "6000-6010"
        volumes:
            - ${APPS_PATH_HOST}/${API_SUBPATH_HOST}:${CODE_PATH_CONTAINER}/${API_SUBPATH_HOST}${CONTAINER_PATH_FLAG}
            - ${PHP_WORKER_LOGS_PATH}:/var/log/worker${CONTAINER_PATH_FLAG}
            - ${PHP_WORKER_CONFIG_PATH}/supervisord.d:/etc/supervisord.d${CONTAINER_PATH_FLAG}
